### ISSUE TITLE
Problem with dataset.

### ISSUE THREAD

**Issue by xufengfan96** [zgojcic/3D_multiview_reg#5]
Hello author,because of the network,I can't use your script files to download the dataset.So I download it from the 3DMatch(http://3dmatch.cs.princeton.edu/).However I noticed that the extract_data.py will need .ply file.And I can only get .png file.So is that mean I should get the some .ply files like the raw pointcloud.Then I can use extract_data.py to get some attribute like features,etc.

**Comment by zgojcic** [comment]
Hi, 

did I get correctly that you cannot download it because of some restrictions on your end? Or is there some problem on our side? If I can somehow assist you in downloading the files let me know. 

Otherwise, the point cloud fragments from 3DMatch dataset are fused from 50 consecutive depth frames. The code for fusion is available [here](https://github.com/andyzeng/3dmatch-toolbox/tree/master/depth-fusion). For the test dataset you can use the matlab code (some lines have to be un/commented for specific scenes please check the code). For the training dataset we modified the `demo.cu` code. Hope this helps you.

Best
Zan

**Comment by xufengfan96** [comment]
Thanks for your responce,
I think the network problem is on my side.And is that means if I want to use my own date.I can use the link about the tools and demo.cu to preprocess first.

**Comment by zgojcic** [comment]
Thanks for your response. If you need any other help with either downloading the data or running the code please open a new issue.
